language: generic

env:
  global:
    - PYTHONIOENCODING=UTF8
    - MPLBACKEND=Agg
    - PYTEST_ADDOPTS='--color=yes'


matrix:
  include:
    # - name: ctapipe=0.8.0
    #   os: linux
    #   env:
    #     - PYTHON_VERSION=3.7
    #     - CTAPIPE_VERSION=v0.8.0

    - name: ctapipe=master
      os: linux
      env:
        - PYTHON_VERSION=3.7
        - CTAPIPE_VERSION=master

  # allow_failures:
  #   - name: ctapipe=master


before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - . $HOME/miniconda/etc/profile.d/conda.sh
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda  # get latest conda version
  - conda info -a # Useful for debugging any issues with conda

install:
  - sed -i -e "s/- python=.*/- python=$TRAVIS_PYTHON_VERSION/g" environment.yml
  - conda env create -n travis python=$PYTHON_VERSION -f environment.yml
  - conda activate travis

  # we install ctapipe using pip to be able to select any commit, e.g. the current master
  - pip install https://github.com/cta-observatory/ctapipe/archive/$CTAPIPE_VERSION.tar.gz
  - pip install -e .

script:
  - pytest -v
